server:
  port: 8081
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
      #defaultZone: http://owagoner:Password123@localhost:8761/eureka/
#  instance:
#    non-secure-port: 80